spring:
  profiles:
    name: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/exBank
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka